### PR TITLE
ensure async errors get bubbled up properly

### PR DESCRIPTION
**Pull request by rjawesome**
Solves https://github.com/biothings/biothings_explorer/issues/671
Includes a stack of the error in the "description" field as I think this would make it easier to debug errors in the future similar to #674  (if necessary I could work on a way to move it somewhere else or just remove it)

### CODE REVIEW

**Comment by tokebe** [comment]
@rjawesome Based on the differences between the the [status](https://github.com/NCATSTranslator/ReasonerAPI/blob/b6a8de72529687fc21e247e599ca4180c22b8089/TranslatorReasonerAPI.yaml#L373-L415) vs [response](https://github.com/NCATSTranslator/ReasonerAPI/blob/b6a8de72529687fc21e247e599ca4180c22b8089/TranslatorReasonerAPI.yaml#L416-L467) formats,  you'll want to amend the [error middleware](https://github.com/biothings/biothings_explorer/blob/5575d3dd03053c9295987d65059c7aace62b1605/src/middlewares/error.js#L48-L54) to detect which endpoint (in the case of asyncquery endpoint errors) and format appropriately. In the case of `asyncquery_response`, you'll want to add the `message` with the query graph and empty kg/results.

Technically, we should also be including the `schema_version` and `biolink_version` for `asyncquery_response` even in the event of errors, but that's minimum-priority.

**Comment by rjawesome** [comment]
Updated (except no biolink_version since that comes from the biolink property)

**Comment by tokebe** [comment]
These changes seem to rather significantly change how the error is handled from your previous iteration -- could you provide an example case of how the response appears now vs. before?

**Comment by rjawesome** [comment]
previous example (asyncquery_response) -- in this iteration asyncquery_response is the same as asyncquery_status:
```json
{
  "job_id": "SHStRcLWyc",
  "status": "Failed",
  "description": "The query graph contains a cycle.",
  "logs": [
    {
      "timestamp": "2023-08-03T16:33:27.837Z",
      "level": "INFO",
      "message": "Expanded ids for node n0: (1 ids -> 1 ids)",
      "code": null
    },
    {
      "timestamp": "2023-08-03T16:33:28.610Z",
      "level": "WARNING",
      "message": "The following APIs were unavailable at the time of execution: Automat-cord19(Trapi v1.3.0)",
      "code": null
    }
  ]
}
```
new example (asyncquery_response) [the full trace is included in the actual message, i just cut it off so this is a bit smaller]
```json
{
  "message": {
    "query_graph": {
      "nodes": {
        "n0": {
          "categories": [
            "biolink:Gene"
          ],
          "ids": [
            "NCBIGene:3778"
          ]
        },
        "n1": {
          "categories": [
            "biolink:Gene"
          ]
        },
        "n2": {
          "categories": [
            "biolink:SmallMolecule"
          ]
        }
      },
      "edges": {
        "e01": {
          "subject": "n0",
          "object": "n1"
        },
        "e02": {
          "subject": "n1",
          "object": "n2"
        },
        "e03": {
          "subject": "n2",
          "object": "n0"
        }
      }
    },
    "knowledge_graph": {
      "nodes": {},
      "edges": {}
    },
    "results": []
  },
  "status": "Failed",
  "schema_version": "1.4.0",
  "workflow": [
    {
      "id": "lookup"
    }
  ],
  "description": "InvalidQueryGraphError: The query graph contains a cycle.",
  "trace": "InvalidQueryGraphError: The query graph contains a cycle.\n    at QueryGraphHandler._validateCycles ...
async /mnt/c/Users/User/Documents/Scripps/biothings_explorer/node_modules/piscina/dist/src/worker.js:141:26",
  "logs": [
    {
      "timestamp": "2023-08-03T16:33:27.837Z",
      "level": "INFO",
      "message": "Expanded ids for node n0: (1 ids -> 1 ids)",
      "code": null
    },
    {
      "timestamp": "2023-08-03T16:33:28.610Z",
      "level": "WARNING",
      "message": "The following APIs were unavailable at the time of execution: Automat-cord19(Trapi v1.3.0)",
      "code": null
    }
  ]
}
```

**Pull request merged**
