### PR TITLE
implement logic to sort servers

### LINKED ISSUE #442: logic to pick API server urls
Right now, when an API (TRAPI or not) is ingested by BTE, BTE picks the first entry in the server list of the SmartAPI yaml. 

However, smarter logic would be nice (what if the first entry isn't the production or encrypted url). Also the Translator consortium may want ARAs to be able to query different sets of KP API servers ("production" vs "development" vs "staging"). 

Here's some ideas for how this logic would work (will have to check the priority of staging vs development):
* production: BTE will only use an API if it has a server url with x-maturity:"production". If it doesn't have any entries with the x-maturity:"production", BTE won't use it (and will log that this is happening). 
    *  if there's more than 1 server url with x-maturity:"production", we could pick the first entry....or try smarter logic like picking the encrypted url (https)
* staging: BTE will use the server urls with x-maturity:"staging" when possible. If an API only has "production" urls, BTE can use those too (with the logic above for production stuff).
* development: BTE will use the server urls with x-maturity:"development" when possible. If an API only has "staging" urls, BTE can use those. If an API only has "staging" and "production" urls, BTE will use the "production" urls (with the logic above for production stuff).

Example SmartAPI registrations with multiple server urls to pick from:
* COHD: http://smart-api.info/registry?q=51c178099fa2dc99b5d8fff8bf9f1a0d
* MyGene: http://smart-api.info/registry?q=59dce17363dce279d389100834e43648

Note that right now some APIs have separate registrations for their production levels, like [ICEES](https://smart-api.info/registry?q=icees) right now...

### PR DESCRIPTION
**Pull request by rjawesome**
Meant to fix [this issue](https://github.com/biothings/BioThings_Explorer_TRAPI/issues/442)

### CODE REVIEW

**Comment by tokebe** [comment]
Currently crashes due to typescript type annotations in a regular js file. You can test this by running `npm run smartapi_sync` (Or running the server with the ENV variable `SYNC_AND_EXIT=true` if you want to use VSCode's debugging) .

**Comment by rjawesome** [comment]
@tokebe Oops, should be fixed (I also tested with the npm command)

**Comment by colleenXu** [comment]
let me know if you want me to test this too, or not. As I noted in the issue, some APIs have multiple endpoints with diff x-maturity levels and others don't

**Comment by tokebe** [comment]
@colleenXu Yes, if you could test to confirm that behavior is as-intended. Currently, a number of development APIs that previously may have been used are being skipped for production. This is in-line with expected behavior from the code and issue description, however I just want you to confirm that we want to be skipping these.

**Comment by colleenXu** [comment]
Note on TRAPI KP registrations:

* Automat KPs: multiple registrations right now. 
    * The ones we use are now "non-ITRB dev / development". 
    * They have separate registrations for each ITRB instance. And these instances don't seem to work right now (NetworkError during queries)
* COHD: multiple registrations right now. 
    * We are using the TRAPI 1.2 instance - which now has all 4 maturity levels (can be used to test this PR). 
    * The TRAPI 1.3 instance seems to have only a "non-ITRB dev / development" right now. 
    * All 5 server URLs are unique. 
* Connections Hypothesis Provider: 1 registration
    * Has 3 server URLs but only 2 are tagged correctly (production, staging). Not sure if the URLs correctly correspond to the staging levels as well...

**Comment by colleenXu** [comment]
TDLR!

I think the code is working correctly / as-expected (I just have the issues / discussion topics in the later posts). I also outline my process here in case others want to use it

---

My checking process:

x-maturity: prod:
* run `INSTANCE_ENV=prod npm run smartapi_sync`. Expect a lot of registrations to have errors (since they don't have a server url with x-maturity tag "production"). for now: I `Got 36 successful requests`. 
    * [COHD](https://raw.githubusercontent.com/WengLab-InformaticsResearch/cohd_api/master/cohd/TranslatorReasonerAPI.yaml) should use the production url: `https://cohd-api.transltr.io/api`
    * [CHP](https://raw.githubusercontent.com/di2ag/chp_metadata/master/smartapi.yaml) should use the production url: `http://chp.thayer.dartmouth.edu`
* run `INSTANCE_ENV=prod USE_THREADING=false npm start`. 
    * Disease MONDO:0004766 -> Disease query would normally hit COHD (and Automat APIs). 
        * The first TRAPI-log correctly notes that a LOT of TRAPI APIs don't have specs/meta_knowledge_graph loaded into BTE (because they're not the right x-maturity level)
        * the correct production url is used for COHD queries
        * COHD edges are in the knowledge_graph
    * Gene NCBIGene:1629 -> Gene query would normally hit CHP (and Automat APIs). 
        * the correct production url is used for CHP queries (but there are no records retrieved)

---

x-maturity: testing:
* run `INSTANCE_ENV=test npm run smartapi_sync`. Expect successfully retrieved TRAPI registrations to be prod stuff or ITRB test stuff (has test.transltr.io in the URL). I `Got 61 successful requests` which is more than the prod sync... 
    * [COHD](https://raw.githubusercontent.com/WengLab-InformaticsResearch/cohd_api/master/cohd/TranslatorReasonerAPI.yaml) should use the testing url: `https://cohd-api.test.transltr.io/api`
    * [CHP](https://raw.githubusercontent.com/di2ag/chp_metadata/master/smartapi.yaml) should use the production url (since it doesn't have a test url, it goes to the next highest thing): `http://chp.thayer.dartmouth.edu`
* run `INSTANCE_ENV=test USE_THREADING=false npm start`. And run the same queries as above...
    * Disease MONDO:0004766 -> Disease: the correct testing url is used for COHD queries
    * Gene NCBIGene:1629 -> Gene: the correct production url is used for CHP queries (but there are no records retrieved)

---

x-maturity: staging:
* run `INSTANCE_ENV=ci npm run smartapi_sync`. Expect successfully retrieved TRAPI registrations to be prod, ITRB test stuff (has test.transltr.io in the URL), or ITRB ci stuff (has ci.translator.io in the URL). I `Got 87 successful requests` which is more than the test sync... 
    * [COHD](https://raw.githubusercontent.com/WengLab-InformaticsResearch/cohd_api/master/cohd/TranslatorReasonerAPI.yaml) should use the staging url: `https://cohd-api.ci.transltr.io/api`
    * [CHP](https://raw.githubusercontent.com/di2ag/chp_metadata/master/smartapi.yaml) should use the staging url: `http://chp-dev.thayer.dartmouth.edu`
* run `INSTANCE_ENV=ci USE_THREADING=false npm start`. And run the same queries as above...
    * Disease MONDO:0004766 -> Disease: the correct staging url is used for COHD queries
    * Gene NCBIGene:1629 -> Gene: the correct staging url is used for CHP queries (but there are no records retrieved)

---

x-maturity: development:
* run `INSTANCE_ENV=dev npm run smartapi_sync`. Expect successful retrieval of nearly TRAPI registrations (there can be other errors or maybe the registration doesn't have x-maturity tag or valid value in the tag...). I `Got 115 successful requests` which is more than the ci sync... 
    * [COHD](https://raw.githubusercontent.com/WengLab-InformaticsResearch/cohd_api/master/cohd/TranslatorReasonerAPI.yaml) should use the development url (notice no transltr.io in url): `https://dev.cohd.io/api`
    * [CHP](https://raw.githubusercontent.com/di2ag/chp_metadata/master/smartapi.yaml) should use the staging url (their x-maturity dev tag uses the wrong spelling, so BTE should pick the next highest x-maturity level with a url which is staging): `http://chp-dev.thayer.dartmouth.edu`
    * Automat APIs should be used in the queries, since they are loaded now...
* run `INSTANCE_ENV=dev USE_THREADING=false npm start`. And run the same queries as above...
    * Disease MONDO:0004766 -> Disease: 
        * the correct development url is used for COHD queries
        * Automat APIs are used for sub-querying (and get records / edges in response)
    * Gene NCBIGene:1629 -> Gene: 
        * the correct staging url is used for CHP queries (but there are no records retrieved)
        * Automat APIs are used for sub-querying (and get records / edges in response)

**Comment by colleenXu** [comment]
What if I don't provide an INSTANCE_ENV value? 
* `npm run smartapi_sync`. Looks like BTE assumes I'm on "prod". Do we want to change this? Assume dev? no assumption so INSTANCE_ENV has to be manually set (not sure how that works in deployment)?
* If I first run `INSTANCE_ENV=dev npm run smartapi_sync` and then...
    * run `USE_THREADING=false npm start` (no INSTANCE_ENV variable set), BTE will act like INSTANCE_ENV=dev (aka use Automat and dev urls). Is that as-expected?
    * run `INSTANCE_ENV=prod USE_THREADING=false npm start` (aka set INSTANCE_ENV to a diff value), BTE will **not** act in the prod manner. Instead, it will act in the dev manner. Is that as-expected? It seems like the INSTANCE_ENV variable affects the cron job / set of specs - and then BTE works with whatever came out of the cron job + matches its config file (for the v1/query endpoint).

**Comment by colleenXu** [comment]
@tokebe Maybe this involves some discussion / clarification from you?

What if I don't provide an INSTANCE_ENV value? 
* `npm run smartapi_sync`. Looks like BTE assumes I'm on "prod". Do we want to change this? Assume dev? no assumption so INSTANCE_ENV has to be manually set (not sure how that works in deployment)?
* If I first run `INSTANCE_ENV=dev npm run smartapi_sync` and then...
    * run `USE_THREADING=false npm start` (no INSTANCE_ENV variable set), BTE will act like INSTANCE_ENV=dev (aka use Automat and dev urls). Is that as-expected?
    * run `INSTANCE_ENV=prod USE_THREADING=false npm start` (aka set INSTANCE_ENV to a diff value), BTE will **not** act in the prod manner. Instead, it will act in the dev manner. Is that as-expected? It seems like the INSTANCE_ENV variable affects the cron job / set of specs - and then BTE works with whatever came out of the cron job + matches its config file (for the v1/query endpoint).

**Comment by colleenXu** [comment]
@tokebe I also think we SHOULD NOT MERGE THIS FOR NOW. 

We should wait for clarification / changes to the TRAPI KP Registrations. [Things](https://github.com/biothings/BioThings_Explorer_TRAPI/pull/467#issuecomment-1195031331) don't seem to be fitting the expected standard (where diff x-maturity stuff can fit under the same registration, and only certain values are expected for x-maturity) https://github.com/NCATSTranslator/TranslatorArchitecture/blob/master/SmartAPIRegistration.md#server-count

**Comment by tokebe** [comment]
@colleenXu Correct, `INSTANCE_ENV` only affects the cron job, which is updated every 10 minutes on any live server. This is expected behavior. 

If `INSTANCE_ENV` is not provided, we default to production, which I think makes sense considering that most of our test cases while developing BTE are testing whether xyz change will work in the production environment. In most cases, no dev (or random person cloning the repo to test things locally) is going to provide this variable (or most variables, which is why we want the vast majority of them to have "sensible defaults" to their behavior), so we want it to default to the most "stable" case. I'd hear arguments against that, but it's what makes the most sense to me.

**Comment by colleenXu** [comment]
I guess I'm not sure right now how stable ITRB prod is >.<. But otherwise I agree with you. 

In today's Architecture call:

* It was confirmed that there's 1 registration per tool (on a specific TRAPI version). So Automat is working on fixing their issue of automatically making separate registrations for every instance. This code should therefore work...
* It was confirmed that people should use the exact x-maturity terms (production, testing, staging, development). Spelling errors can be pointed out to the team in charge of the tool. 
* Tyler Beck set a deadline for August 29th - all tools should have a server url with x-maturity:production and that url is for the ITRB prod instance. 

If this deadline is met....

And the TRAPI 1.2 -> 1.3 complication is handled (tools should have separate registrations for TRAPI 1.3 - and the server urls in those registrations should increase as the deadlines pass to push TRAPI 1.3 into staging/testing/production).....

Then I think we can re-test and consider merging / using this....

**Comment by colleenXu** [comment]
so maybe this PR and the issue can be moved to the on-hold bucket (project manager) for now...

**Comment by tokebe** [comment]
I agree with your assessment. I will say that whether ITRB Prod is stable or not (our instance or other teams'), it's *supposed* to be the stable production release, so AFAIK we should always assume that prod is the most stable option. 

If there are exceptions to that, I would think we'd want to add exceptions in some form of config, rather than changing our assumption. Possibly something to consider as an additional feature in this issue if the need arises.

**Comment by colleenXu** [comment]
current situation being tracked in this issue https://github.com/biothings/BioThings_Explorer_TRAPI/issues/472#issuecomment-1230876158. TDLR: COHD and CHP have 1 registration/multiple server urls where this logic could be useful. Automat still doesn't...

**Comment by tokebe** [comment]
@colleenXu Given what you said and that the August 29th deadline is now passed, do we want to look into merging this?

**Comment by colleenXu** [comment]
I'm still waiting because of the Automat API situation....I did ask (internal Translator Slack [link](https://ncatstranslator.slack.com/archives/CSS752SB0/p1661808284170719)) but haven't had a response yet.

**Comment by tokebe** [comment]
@colleenXu Would fallback behavior for multiple registrations make sense to be able to move forward with this issue?

**Comment by colleenXu** [comment]
I'm not sure what "fallback" behavior means - and what info would need to be in the config / include list in order to do this @tokebe

**Comment by tokebe** [comment]
@colleenXu If the reason we're not moving forward with this issue is because there is a case of an API not using a single registration with multiple-server notation, would it not make sense to implement (as part of the logic for this PR) a check that runs first for multiple registrations per-server for the same API, and then handle those multiple registrations as if they were a single registration? 

I don't believe any additional configuration info would be required, just a well-defined set of expectations for handling this case.

**Comment by colleenXu** [comment]
This might be worth doing, depending on how quickly we think the Automat team can deploy their fix. I'm not sure...

----
Pasted from https://github.com/biothings/BioThings_Explorer_TRAPI/issues/472#issuecomment-1230876158

Note: we're currently using the ITRB-prod registrations for all Automat APIs. However, it's not clear if the Automat team currently has access to those instances (ITRB prod / test). ITRB-CI / dev might be more reliable at the moment.

Received update from Chris Bizon (internal Translator Slack [link](https://ncatstranslator.slack.com/archives/CSS752SB0/p1666024311149929)): they plan on changing their registrations to have 1 per tool in the next few weeks.

**Comment by tokebe** [comment]
That being the case, and given that the consortium appears to be moving toward single-registration as a standard, I'd say it's probably worth just waiting out unless getting the PR merged suddenly became a high priority.

**Comment by tokebe** [comment]
After further testing, I've confirmed that this PR only affects TRAPI APIs. Server selection for TRAPI APIs is done in the cron job, however all non-TRAPI APIs select their servers [here](https://github.com/biothings/smartapi-kg.js/blob/34ad3a26dbe7960485f04a5de87194f8fc19ba21/src/parser/index.ts#L82-L87).

The existing logic in this PR will have to be duplicated there.

**Comment by rjawesome** [comment]
@tokebe In that case I'll reopen [my previous PR](https://github.com/biothings/smartapi-kg.js/pull/52) which should achieve that objective.

**Comment by colleenXu** [comment]
Testing process:

* with https://github.com/biothings/smartapi-kg.js/pull/52
* Based on requirements in [these](https://github.com/biothings/BioThings_Explorer_TRAPI/issues/442#issuecomment-1178293171) [comments](https://github.com/biothings/BioThings_Explorer_TRAPI/issues/442#issuecomment-1178297749)
* Also following previous [testing](https://github.com/biothings/BioThings_Explorer_TRAPI/pull/467#issuecomment-1195042687) process
* At the moment:
    * automat apis list their staging url first. They have all 4 x-maturity urls (dev urls use "renci")
    * cohd has all 4 x-maturity urls and lists the prod url first
    * chp has 3 x-maturity urls (no dev) and lists the prod url first
* Special testing:
    * biothings apis list their encrypted url first, so I'll need to use a local edited file where the encrypted url is listed 2nd for testing (smartapi-override)

<details>
<summary>prod</summary>

* run `INSTANCE_ENV=prod npm run smartapi_sync`. Some APIs correctly have error messages in the console-logs because the x-maturity level is too low. The console-logs show that the correct prod urls were picked up for automat, COHD, and CHP APIs. 
```
  bte:biothings-explorer-trapi:cron [error]: Unable to parse spec, CAM-KP API. Error message is Error: Server https://cam-kp-api.test.transltr.io/1.3.0 skipped due to insufficient maturity level testing +27ms
  bte:biothings-explorer-trapi:cron [error]: Unable to parse spec, SRI Reference Knowledge Graph API (trapi v-1.3.0). Error message is Error: Server https://automat.renci.org/sri-reference-kg/1.3 skipped due to insufficient maturity level development +0ms
```

* run BTE `USE_THREADING=false npm start`
* query: `Disease MONDO:0004766 -> PhenotypicFeature`. Correctly uses prod urls for automat (`https://automat.transltr.io/cord19/1.3/query`), COHD (`https://cohd-api.transltr.io/api/query`).
    * The first TRAPI-log correctly notes that the CAM-KP and SRI KG APIs don't have specs/meta_knowledge_graph loaded into BTE (because they're not the right x-maturity level)
```
        {
            "timestamp": "2022-11-04T01:27:33.886Z",
            "level": "WARNING",
            "message": "The following APIs were unavailable at the time of execution: CAM-KP API, RTX KG2 - TRAPI 1.3.0, SRI Reference Knowledge Graph API (trapi v-1.3.0), Knowledge Collaboratory API, Automat-mychem-info(Trapi v1.3.0), CAM-KP API, Service Provider TRAPI, SRI reference KG (ITRB DEV) (trapi v-1.3.0), CAM-KP API, Automat-icees-kg(Trapi v1.3.0), SRI reference KG (ITRB DEV) (trapi v-1.3.0), Automat-covidkop(Trapi v1.3.0)",
            "code": null
        },
```

* query: `Gene NCBIGene:672 -> AnatomicalEntity`. Correctly uses prod urls for CHP (`https://chp-api.transltr.io/query`), automat (`https://automat.transltr.io/cord19/1.3/query`)

</details>


<details>
<summary>test, staging, dev</summary>

Test:

* run `INSTANCE_ENV=test npm run smartapi_sync`. `SRI Reference Knowledge Graph API` correctly has error messages in the console-logs because the x-maturity level is too low. The console-logs show that the correct prod urls were picked up for automat (https://automat.test.transltr.io/gtopdb/1.3), COHD (https://cohd-api.test.transltr.io/api), and CHP (https://chp-api.test.transltr.io) APIs. 

Staging:

* run `INSTANCE_ENV=ci npm run smartapi_sync`. `SRI Reference Knowledge Graph API` correctly has error messages in the console-logs because the x-maturity level is too low. The console-logs show that the correct prod urls were picked up for automat (https://automat.ci.transltr.io/gtopdb/1.3), COHD (https://cohd-api.ci.transltr.io/api), and CHP (https://chp-api.ci.transltr.io) APIs. 

Dev:

* run `INSTANCE_ENV=dev npm run smartapi_sync`. No errors for x-maturity level being too low. The console-logs show that the correct prod urls were picked up for automat (https://automat.renci.org/gtopdb/1.3), COHD (https://cohd.io/api but got an error 502), and CHP (uses staging url since it doesn't have a dev url listed; https://chp-api.ci.transltr.io) APIs. 

</details>

<details>
<summary>special testing for encrypted prod urls</summary>

* Modify a local yaml file for MyChem.info. Switch the order of the server urls so the encrypted prod is second
* put in an override in bte-trapi's `src/config/smartapi_overrides.json` so MyChem will use the local file. 
* run `API_OVERRIDE=true npm run smartapi_sync`
* run BTE `USE_THREADING=false npm start`
* query for MyChem specifically (`http://localhost:3000/v1/smartapi/8f08d1446e0bb9c2b323713ce83e2bd3/query`): `SmallMolecule CHEMBL.COMPOUND:CHEMBL941 -(treats)-> Disease`. 
    * In console-logs, I see that BTE correctly uses encrypted prod url  (the 2nd url): `https://mychem.info/v1/query`

</details>

**Comment by colleenXu** [comment]
Testing done, with https://github.com/biothings/smartapi-kg.js/pull/52. Looks good! 

During deployment, we'll want to make sure the `INSTANCE_ENV` variable is correctly set and being used in the cron jobs for each instance...

**Comment by tokebe** [comment]
`INSTANCE_ENV` Has already been set in ITRB servers, I'll set it in dev. Other than that, I'll get this merged ASAP.

**Pull request merged**
