### PR TITLE
feat: add biothings suppkg to config

### PR DESCRIPTION
**Pull request by colleenXu**
will allow use by team-specific endpoints and ara
related to https://github.com/biothings/biothings_explorer/issues/706

### CODE REVIEW

**Comment by colleenXu** [comment]
@tokebe 

We may want to pause on deploying this, for reasons besides the code-freeze on test/prod
* if we wanted to avoid TRAPI-validator errors / allow the UI to handle these infores, we'd want [Translator's infores catalog to be updated with the infores IDs used](https://github.com/biolink/biolink-model/pull/1391) AND for downstream resources to use this updated infores catalog (UI? are there other downstream Translator resources? reasoner-validator / ARAX UI?)
* I'd like to wait for a reply from Yao and Andrew on my [post](https://github.com/biothings/biothings_explorer/issues/706#issuecomment-1715134708)

**Comment by colleenXu** [comment]
@tokebe 

There's one more issue to resolve, then this is ready to deploy:
* whether the UI is using a "version" of the infores registry w/ suppKG info (see my Translator Slack [post](https://ncatstranslator.slack.com/archives/C03LX327RK8/p1697693837755999) asking about this) - this is so the UI can display provenance information properly for edges from this KP

The "UMLS:DC" IDs issue has been resolved for now, since I discussed things with Andrew after [his latest reply](https://github.com/biothings/biothings_explorer/issues/706#issuecomment-1757994804)

**Comment by colleenXu** [comment]
Belated update: the issue above has been resolved. So we can move ahead with deployment

The infores registry changes for suppKG and TTD are [here](https://github.com/biolink/biolink-model/pull/1391). UI team said yesterday (Translator Slack link)
> the UI ingested the infores catalog 3 weeks ago and I verified it includes the changes you posted above

**Comment by tokebe** [comment]
Superseded by biothings/bte-server@58177d37ddb66c52ae3a732aecb0ddfa79257cd4

Future changes to the api list will happen in https://github.com/biothings/bte-server

**Pull request closed without merging**
