### PR TITLE
#456: add diagram of query handling

### PR DESCRIPTION
**Pull request by ericz1803**
#456 This PR adds a sequence diagram of a high-ish level overview of how a TRAPI query is executed. Feel free to make comments on any suggestions or changes that should be made to the diagram.

### CODE REVIEW

**Comment by colleenXu** [comment]
hmmmm...the diagram is kinda hard to read in github's dark mode, for me....I had to switch my github appearance setting to light mode for it to be easier to read...

**Comment by tokebe** [comment]
This is awesome. I'm sure I missed some discussion in-meeting regarding additional details and formatting, but I think that with just a little more polish this will be perfect for introducing BTE's operation. 

I wonder if it'd make sense to make additional diagrams for more specific behaviors in certain modules later on?

**Comment by ericz1803** [comment]
@colleenXu: I got rid of the coloring so it is easier to see in all color themes.

@tokebe It definitely could make sense, the only tradeoff is more maintenance and possibility of going out of date.

**Comment by tokebe** [comment]
Agreed, there's probably a balance to be struck that's worth further discussion.

Also, I think the bounding box for the alt ("If there are uncached results") has changed in the latest commit?

**Comment by ericz1803** [comment]
Good catch, just fixed it

**Comment by colleenXu** [comment]
https://github.com/biothings/BioThings_Explorer_TRAPI/pull/491#issuecomment-1222459905 @tokebe I mentioned some specific modules/tasks that there could be sub-diagrams for....during the past group-meeting (when you were out). see the group meeting notes...

**Pull request merged**
