### PR TITLE
feat: :sparkles: Add BTE landing page

### PR DESCRIPTION
**Pull request by marcodarko**
BioThings Explorer landing page added

Screen Shot 2023-03-10 at 1 13 29 PM

### CODE REVIEW

**Comment by marcodarko** [comment]
Issues executing queries with my local setup but providing this can be fixed this new addition shouldn't interfere with any of the workspace functionality as it's all frontend related and completely separate.

**Comment by tokebe** [comment]
Added a postinstall for automated building, and opened a [supporting PR](https://github.com/biothings/bte-trapi-workspace/pull/22) for integration into the workspace without errors

**Comment by tokebe** [comment]
@marcodarko Opening the `about` and `try it` pages in a new tab currently results in a `cannot GET` error.

**Comment by marcodarko** [comment]
@tokebe uh-oh ok I'll take a look at this issue, glad to hear the other issue is taken care of for now

**Comment by tokebe** [comment]
note: all tests work on local, this is likely an issue due to the workspace. Will solve with workspace migration.

**Pull request merged**
