### PR TITLE
Mock axios calls in tests

### PR DESCRIPTION
**Pull request by rjawesome**
Mocks axios calls in tests. https://github.com/biothings/BioThings_Explorer_TRAPI/issues/541

### CODE REVIEW

**Comment by tokebe** [comment]
I'm sorry to request this as I know it's an annoying bunch of edits, but it'll be a lot better for future readability to make use of [jest.MockResolvedValueOnce()](https://jestjs.io/docs/mock-function-api#mockfnmockresolvedvalueoncevalue) to mock the async return values within the specific tests, if possible.

**Comment by rjawesome** [comment]
I was wondering how I should do this because I don't think it would make sense to rely on the order of API calls within a specific test. Should I find the tests that have only one api call and then apply this logic to those, or should I just find the order of API calls for all tests and mock resolved values based on that?

**Comment by tokebe** [comment]
Sorry, I hadn't considered that. You could try breaking up the large implementation mock into a mock implementation per test, as shown in the [first answer here](https://stackoverflow.com/questions/48790927/how-to-change-mock-implementation-on-a-per-single-test-basis), which would be sufficient for clarity.

**Comment by rjawesome** [comment]
Should be mostly fixed (I need to check up on failing test)

**Pull request merged**
