### PR TITLE
API_LIST override behavior + some refactoring

### PR DESCRIPTION
**Pull request by tokebe**
- Moved `src/routes/v1/config.js` to `src/config/apis.js` to make its location more obvious
- by_team and by_api endpoints now respect the `API_LIST`
- Added an env variable `IGNORE_API_LIST` to bypass API list and allow use of any API, defaults to false.
- API_OVERRIDES now change the `API_LIST`:
  - By default, APIs added to overrides are added to the `API_LIST`. This can be disabled in the `smartapi_overrides.js` config by setting `override_API_LIST` to `false`.
  - If `only_overrides` is `true`, the API list is set to only the overridden APIs.

### CODE REVIEW

**Comment by colleenXu** [comment]
### First, I'm not sure if this code works as-intended. 

I went on the branch and wanted to test whether the apis-specific and team-specific endpoints only accept IDs from the `API_LIST` in the config file. 

1. Remove BioThings Rhea API entry from `API_LIST` (I comment it out) in the file `src/config/apis.js` . I then saved this change, and tried to make sure it was implemented. I went to the top directory (`bte-trapi-workspace`), did `npm run compile`, and did `npm run smartapi_sync --workspace='@biothings-explorer/bte-trapi'`. 
2. Then I started up BTE and tried running a query (see the collapsed query at the bottom of this post) to the Rhea API through the api-specific endpoint (http://localhost:3000/v1/smartapi/03283cc2b21c077be6794e1704b1d230/query). 
3. I expected something like an empty TRAPI response with the logs "no metaKG edges found" (see first note [here](https://github.com/biothings/BioThings_Explorer_TRAPI/pull/448#issuecomment-1136837805) for why this is kinda confusing). Instead, it ran using Rhea just fine and returned a response.....this is the same as the current behavior (main branch), where this endpoint doesn't care about API_LIST. 

EDIT: I also tried running with `IGNORE_API_LIST=false npm start`....and this still happens for the api-specific and team-specific endpoints. Only the v1/query endpoint will exclude the Biothings Rhea API (like it's paying attention to the API_LIST). 

<details>
<summary> query for Rhea api</summary>

```
{
    "message": {
        "query_graph": {
            "nodes": {
                "n0": {
                    "categories": ["biolink:MolecularActivity"],
                    "ids": ["RHEA:21429", "RHEA:15533", "RHEA:10024"]
                },
                "n1": {
                    "categories": ["biolink:SmallMolecule"]
                }
            },
            "edges": {
                "e01": {
                    "subject": "n0",
                    "object": "n1"
                }
            }
        }
    }
}
```
</details>

**Comment by colleenXu** [comment]
### Second, I find this PR confusing >.<. 

There seems to be 4 variables now? And it's not clear to me:
* how they affect each other's behavior (are some prioritized over others)
* what combos of settings / commands should be used for testing new SmartAPI files / registrations or editing x-bte annotation
* are there combos that don't make sense / would lead to buggy behavior, and is there error handling for these scenarios? 

---

I'll go through the 4 variables and my understanding of this PR.....this is a major brain dump though so I'm not sure how much sense I'll make:

* `API_OVERRIDE`: 
    * default `false`. 
    * setting it to `true` means that BTE will pay attention to what's in the `smartapi_overrides.js` (not json anymore) file. Otherwise, BTE doesn't use anything in that file, which makes sense since there isn't any overrides. 
    * I use it mostly with the `npm run smartapi_sync --workspace='@biothings-explorer/bte-trapi'` command. 
* `IGNORE_API_LIST`: 
    * default `false`. 
    * This PR is meant to stop api-specific and team-specific endpoints from accessing APIs that aren't in the `API_LIST` when the value is `false`. But as I noted in my earlier post, I'm not sure about that this behavior is happening....
    * It's not clear to me when this variable would be changed (set to `true`) when testing new SmartAPI files / registrations or editing x-bte annotation......except maybe 1 situation (see the last variable). But then I get confused (see the last section of this post on "all variables true"). 
* `override_API_LIST`:
    * default `true`. 
    * It's not clear to me when this variable would be changed (set to `false`) when testing new SmartAPI files / registrations or x-bte annotation. Since this testing involves using whatever I put in the `apis` object of the overrides file, and it sounds like with this PR, everything I'm testing needs to be the `API_LIST` to be accessible...
    * Does this work when I test a new SmartAPI file? I didn't know `API_LIST` could use entries that don't have a SmartAPI registration ID. 
    * what happens if I'm testing edits to a SmartAPI yaml corresponding to an existing element in `API_LIST`? Does this variable affect that kind of testing? What I currently do is: make an entry in the `apis` object that uses the same SmartAPI registration ID as the existing element, but links to my local file; then I'd set `API_OVERRIDE` to true when running the sync/cron job; then I can test my local file (usually I only use the api-specific endpoint). 
* `only_overrides`: 
    * default: `false`
    * seems like when this variable is set to `true`, there would be issues if `overrides_API_LIST` and `IGNORE_API_LIST` were both `false` and I was trying to test by making entries in the `apis` object. Is that right? And then....does setting either of those variables to `true` have the same effect? Hmm....
    * EDIT: I see in the opening post now, that `only_overrides: true` should cause `overrides_API_LIST:true` automatically, If I'm understanding this 
    > If only_overrides is true, the API list is set to only the overridden APIs.

---

But then what happens if all 4 variables are true?

When would I ever want to do that? Maybe I was testing multiple things at once? 

But then what if: 
* there was an existing SmartAPI registration w/ x-bte annotation but it wasn't in the `API_LIST`
* I want to make local edits to a file and test this edited file 
* and all 4 variables are true. 

Thinking it through....
* First the existing SmartAPI registration would be pulled into BTE because `IGNORE_API_LIST=true`
* then what? Maybe behavior depends on whether I set the entry in the `apis` object to the same ID as the existing SmartAPI registration, vs a different arbitrary ID? 
* It's not clear to me if the existing SmartAPI registration would be used by BTE or my local file would be used or both...(see the post below, I think both would be used if a different arbitrary ID was used for the `apis` object since that's what is happening now in the main branch...)

**Comment by colleenXu** [comment]
### Note 1
Edited from Slack: actually I think it's confusing that we don't have an error / special message if I try to put a smartapi ID that doesn't exist into the api-specific endpoint. It'll return an empty TRAPI response with logs saying no smartapi edges are found, which isn't the same as saying "that SmartAPI ID doesn't exist in the first place". 
* I think this could instead be an TRAPI response for an error (I'd have to read up on TRAPI, I remember top-level properties, something with status / code / description / message). There'd be something stating `This API ID isn't recognized by BTE, please check the config list, value of environmental variables like API_OVERRIDE, and contents of config files like src/config/smartapi_overrides.json`

### Note 2
The situation with the "4 variables all true"....actually I can get "two versions of the same api" queried right now (on the main branch). 
1. in `smartapi_overrides.json`, keep `only_overrides` as `false` and add an entry for Rhea SmartAPI yaml using a different arbitrary ID - I use `lalala` and set the value to my local file (which is the same as the current registration; one can also use the url to the file in the translator-api-registry repo). 
2. set `API_OVERRIDE=true` (I run the sync/cron job). 
3. run BTE locally, and query the team-specific endpoint for Service Provider with a Rhea query (see my first post's collapsed section at the end)
4. count the number of sub-queries to the rhea api. there'll be 8, but there's only 4 unique queries. This is because there are two sets of identical sub-queries: one to the "lalala" entry AND another to the existing SmartAPI registration. You can compare by running the api-specific endpoint for "lalala" or the existing SmartAPI registry ID (there'll be only 4 sub-queries). 
    * further notes: this works even if Rhea is removed from the `API_LIST` variable in the config file, because BTE main branch doesn't use the `API_LIST` for the team-based endpoint.

**Comment by tokebe** [comment]
There's a lot to cover here... 

- I'll start with the obvious failure of the by_team and by_api endpoints to respect the `API_LIST` -- I think this is due to the `smartapi-kg` using different loaders for those endpoints, which themselves don't check for `API_LIST`. I missed this in my initial implementation. I'm going to see if it's viable to refactor some of this package to be more straightforward.
- I also agree there should be some sort of specific error for nonexistent IDs on the api specific endpoint, and probably a similar error for nonexistent teams on the team specific endpoint. I'll roll that behavior into this PR.

With regard to your other questions:

- `IGNORE_API_LIST` doesn't currently have an expected use-case, however it seemed reasonable to include in case a use-case becomes apparent.
- `override_API_LIST` likewise doesn't have an expected use-case currently but was added because it felt reasonable to assume it may be useful at some point. 
  - The behavior currently adds ids to the `API_LIST` without checking prior existence because the `API_LIST` is only used by checking id inclusion AFAIK, however it makes sense to not add additional instances of existing ids, so I'll fix that.
  - Either way there should be no interaction with testing on existing/enabled APIs. If you override an existing API, it's replaced and is already in the list so it will remain enabled. If you set `override_API_LIST` to `false`, the `API_LIST` is not modified in any way.
  - I did also miss disabling this if `API_OVERRIDE` isn't enabled because of a bad assumption on my part.
- Given: `only_overrides: true, override_API_LIST: false, IGNORE_API_LIST: false` (and assuming `API_OVERRIDE: true`), and you were adding entries to the `API_LIST`: 
  - Your overrides in the smartapi specs would be the only available entries, and whatever is enabled in the `API_LIST` would be "allowed", so if your overrides were manually added to the `API_LIST`, they'd be the only available APIs despite others being "allowed" by the `API_LIST`. I don't see where you would expect problems? Enabling `override_API_LIST` on top of this would remove any entries you added to the API_LIST, and add entries from your overrides in `smartapi_overrides.json`.
  - I think there might be some confusion as to the purpose of the `override_API_LIST` behavior: The point is to *not have to* add entries by hand to the `API_LIST` when adding "new" overrides. If you're after a specific setup that's not easily provided by automation, you can use these config options to ensure that (e.g. specific APIs enabled in the API_LIST that aren't in your overrides, while using `only_overrides`, though I'm not sure why you'd want that...)

# Let me try to clarify the hierarchy (given intended behavior that will be present after some fixing):

- `API_OVERRIDE`: If this is disabled, anything to do with overriding is disabled. The `API_LIST` will not be touched.
- `IGNORE_API_LIST`: Independent of everything else. If enabled, the `API_LIST` is ignored and no APIs are disabled. Doesn't interact with `API_OVERRIDE`, etc -- any changes to the `API_LIST` due to manual editing or automatic overriding are moot because the `API_LIST` is ignored.
- `override_API_LIST`: Automatically add additional overrides from the `smartapi_overrides.js` to the `API_LIST`. `API_LIST` isn't modified if disabled, or if enabled but `API_OVERRIDE` isn't enabled. If `only_overrides` is also enabled, removes all non-override entries from the `API_LIST`.
- `only_overrides`: Removes non-override APIs from the list if `API_OVERRIDE` is enabled. See above for interaction with `override_API_LIST`.

# To sum it up:

So, if you just wanted to add a couple "new" APIs for testing via an override:

- Add them to `smartapi_overrides.js`.
  - If you want only the override APIs to be available to BTE, enable `only_overrides`.
- Run `API_OVERRIDE=true npm run smartapi_sync` from the workspace.
- Run BTE with `API_OVERRIDE=true`.
  - The default behavior will add your new overrides to the `API_LIST`, enabling them for use.

The exact same workflow can be used for overriding already-existing APIs which are already on the `API_LIST` without worry.

The assumption is generally that if you're overriding an API, you probably want to test it, and therefore want it enabled in the API_LIST. Part of the point here is to streamline that. If you want to do something else, the other options allow setting up those stranger edge-cases.

**Comment by tokebe** [comment]
After [a question asked in the Slack](https://suwulab.slack.com/archives/CC218TEKC/p1653505990530339) I have some concern if we're correctly applying the API_LIST as intended and some confusion regarding that...

Currently, the general endpoints use the `sync_operations_builder_with_reasoner` while the specific endpoints use the `sync_operations_builder`. It would appear that the former applies the API_LIST to only the TRAPI operations, while the latter doesn't employ TRAPI operations.

Should this be the case? Should the API_LIST be applied to filter non-TRAPI operations as well? This would be required given the current setup if we're going to have the by_team and by_api endpoints respect it.

Tagging @colleenXu @newgene for comments.

**Comment by colleenXu** [comment]
To clarify, are you saying that the current situation is: 
* BTE isn't using API_LIST to pick out the non-TRAPI APIs it'll use. This is happening for all endpoints - even though we originally noticed the issue in api-specific and team-specific endpoints. 
    * this is a bit surprising since it really seemed like the general endpoint was only using the stuff specified in API_LIST (it's hard to tell now since I removed all APIs from the registry that we didn't keep in API_LIST)
* So if we added an API with all the x-translator/x-bte annotation to the registry, but not to the API_LIST...BTE would pick up and use this API for all endpoints

**Comment by colleenXu** [comment]
And some thoughts on "desired behavior" (brain-dump, not concrete):

I thought there was tentative agreement by @andrewsu @newgene and me that:
* default BTE behavior (not a dev / testing smartapi yamls) should use the API_LIST as the full set of APIs that BTE uses
    * But the team-specific and api-specific endpoints only need to work with a subset of the API_LIST - the non-TRAPI APIs. As mentioned by Chunlei in [Slack](https://suwulab.slack.com/archives/CC218TEKC/p1653520868419869?thread_ts=1653505990.530339&cid=CC218TEKC). 
* It seemed like "testing" behavior is something to still discuss (I haven't fully digested Jackson's reply to all my posts above).
    * We still want to be able to test local smartapi yamls. These are smartapi/x-bte annotation (not TRAPI). These may be totally new or modified versions of APIs that are already registered and in the API_LIST.
        * almost of the time, I'd only need to use the api-specific endpoint
        * I have tried using the other endpoints, but only for specific reasons:
            * does the test-API work well with other APIs in a full query? This can be "how is speed / performance after adding this api" or "does a multi-hop now work better because the test-API provides more input IDs to some hops".
            * is the test-API going to get picked up and used by the team-specific endpoint? I think this check is not important (it should be picked up). 
    * If I'm testing a modified version, do we need to worry about "overriding" the already registered thing? I'm okay with what I think the current behavior is: (1) if I link my modified-API to the same key (registration ID), the override does happen - and I can then put that key in the api-specific endpoint and test the modified-API, VS (2) if I link my modified-API to a different key, the override doesn't happen - and that's fine since I'll mostly test 1 API at a time with the api-specific endpoint.

And a side note on testing: we still want to be able to test TRAPI apis. This normally means modifying API_LIST locally to add the TRAPI API's registration info. Then we can test it with BTE using the general v1/query endpoint. When we want to test it alone or with a small group of other APIs, we can always modify API_LIST locally (comment out other APIs)

**Comment by colleenXu** [comment]
I've reread all the comments on this post. Now that I've partially digested @tokebe's [big reply](https://github.com/biothings/BioThings_Explorer_TRAPI/pull/448#issuecomment-1137480638).....the intended behavior of this PR makes a more sense to me. It seems okay....but still somewhat complex....like there may be a chance of unintended consequences / bugs from this refactoring. 

---

It seems like there are a few "what is the current behavior vs desired behavior" issues to discuss (after the Relay?):
* What is going now with the API_LIST variable and the endpoints? I'm thinking of Jackson's first section / first point [here](https://github.com/biothings/BioThings_Explorer_TRAPI/pull/448#issuecomment-1137480638) (smartapi-kg package?) and the second paragraph [here](https://github.com/biothings/BioThings_Explorer_TRAPI/pull/448#issuecomment-1143953724)  on the `the `sync_operations_builder` things
* What do we want the "default" desired behavior to be, regarding the API_LIST and the endpoints?
    * I think we've decided that we want the API_LIST to be respected for all endpoints, plus extra checks for non-valid inputs for team and api-id (first section / second point [here](https://github.com/biothings/BioThings_Explorer_TRAPI/pull/448#issuecomment-1137480638))
    > I also agree there should be some sort of specific error for nonexistent IDs on the api specific endpoint, and probably a similar error for nonexistent teams on the team specific endpoint. I'll roll that behavior into this PR.
* What do we want the behavior to be in a testing/dev environment? AKA what environmental / special variables
    * That's what the earlier posts + Jackson's big reply + my first section in this post are discussing. I think there's some agreement but I think this would definitely benefit from others' feedback and some more discussion (walking through the stuff again :P)

**Comment by tokebe** [comment]
Closing this PR as the changes it covers are being broken up into separate PRs. Discussion regarding testing behavior can continue in a new PR.

**Comment by colleenXu** [comment]
Noting: I think this is the new PR https://github.com/biothings/BioThings_Explorer_TRAPI/pull/458

**Pull request closed without merging**
