### PR TITLE
Add qualifiers

### PR DESCRIPTION
**Pull request by tokebe**
Update broken tests, smartapi spec, hard-cached specs to support qualifiers and biolink 3.1.1

Related PRs:
- https://github.com/biothings/api-respone-transform.js/pull/41
- https://github.com/biothings/call-apis.js/pull/63
- https://github.com/biothings/bte_trapi_query_graph_handler/pull/129
- https://github.com/biothings/smartapi-kg.js/pull/63
- https://github.com/biothings/biolink-model.js/pull/32

### CODE REVIEW

**Comment by colleenXu** [comment]
@tokebe Does this PR need the custom https://github.com/biothings/BioThings_Explorer_TRAPI/blob/dev/src/config/smartapi_overrides.json that's on dev right now?

Also, I made PRs for the x-bte annotation. However, I suggest waiting to merge them until all instances are ready to move to qualifiers/biolink3...
* https://github.com/NCATS-Tangerine/translator-api-registry/pull/106 for ours
* https://github.com/NCATS-Tangerine/translator-api-registry/pull/107 and https://github.com/NCATS-Tangerine/translator-api-registry/pull/105 for Text mining.

**Comment by tokebe** [comment]
I don't think we need the overrides, as these PR branches are merged into dev, which has the overrides. Once we start deploying to CI/Test/Prod, then we'll want to just update the annotations I think. Unless you mean that should wait until other ARAs and KPs are ready to move this feature to Prod?

**Comment by colleenXu** [comment]
@tokebe 

Okay, it sounds like for the overrides...
* we'll have to be careful merging to dev, since we'll want to keep the overrides currently in dev
* we plan to deploy to ci/test/prod instances all at once, so around that time, we'll merge the PRs for the registry and refresh the registry. 

I think we're waiting to deploy to ci/test/prod until Translator tells us it's okay to do so?

**Comment by colleenXu** [comment]
Addresses https://github.com/biothings/BioThings_Explorer_TRAPI/issues/512 and https://github.com/biothings/BioThings_Explorer_TRAPI/issues/514

**Pull request merged**
