### PR TITLE
update API list to add iDISK, other Automat APIs

### PR DESCRIPTION
**Pull request by colleenXu**
EDIT: defunct, this PR does still address #256 

> currently BTE's querying of Automat APIs isn't working since:
> - they changed their names
> - some APIs were recently taken offline
> 
> This PR addresses this problem. Related to #256 
> 
> It also adds comments about other Automat APIs we may want to consider adding (or using to replace Service Provider APIs...)

### CODE REVIEW

**Review by andrewsu — APPROVED** [review]

**Comment by newgene** [comment]
@colleenXu can you apply your changes over @ericz1803's PR https://github.com/biothings/BioThings_Explorer_TRAPI/pull/259? It's ID-based now and merged into `main` now.

**Comment by colleenXu** [comment]
@newgene I can update this PR based on the current main.

**Comment by colleenXu** [comment]
behavior with local instance:
- BTE is querying iDISK API after the cron job (to update SmartAPI specs?). Has the issues previously written out [here](https://github.com/biothings/BioThings_Explorer_TRAPI/issues/261#issuecomment-903439644)
- BTE is getting answers from these Automat APIs:
  - CORD19, Covidkop, CTD, hetio, hmdb, ontology-hierarchy, pharos, robokop, text-mining, uberongraph
  
---

Background:

- Queries that are returning answers from Automat APIs:
  - ChemicalEntity CHEBI:3558 -> Gene uses Automat CORD19, CTD, Pharos
  - PhenotypicFeature HP:0004382 -> Disease uses Automat Ontology Hierarchy, Covidkop
  - Disease MONDO:0009747 -> Gene uses Automat Robokop, Uberongraph (as well as Covidkop)
  - ChemicalEntity CHEBI:30830 -> Disease uses Automat HMDB (as well as CORD19)
  - Disease MONDO:0011565 -> Disease uses Automat Hetio (as well as CORD19, Covidkop, Ontology Hierarchy, Robokop, Uberongraph)
  - AnatomicalEntity UBERON:0001905 -> AnatomicalEntity uses Automat Text Mining (as well as Uberongraph)

**Comment by colleenXu** [comment]
BTE does not seem to get answers from these Automat APIs:

  - Chemical Normalization (uses ChemicalSubstance) 
  - Foodb, Gtex, Gtopdb, hgnc, human GOA, intact, panther, viral proteome (using [examples](https://github.com/NCATSTranslator/testing/tree/main/onehop/test_triples/KP/Ranking_Agent))

**Comment by colleenXu** [comment]
@andrewsu @newgene this issue is ready for review (and merging?).

- note that the addition of more APIs does make BTE take longer (but I didn't notice time-outs or queries longer than 1.5 min on my local instance)

To help with the review:
- The addition of iDISK and more Automat APIs happens in this [commit](https://github.com/biothings/BioThings_Explorer_TRAPI/pull/262/commits/0aa61c75121c485765744fa1cc65585d1b67d221) 
- The previous [commit](https://github.com/biothings/BioThings_Explorer_TRAPI/pull/262/commits/845dd2518260636509dc7b9ba196b1600363be9c) reorganized the list to make it easier to read (and see what type of API this is)
- The 2 posts above are from my testing process. I couldn't figure out how to get answers from some Automat APIs...
- tests pass on my local instance (except the smartapi-kg one that's unrelated)

**Pull request merged**
